name: 'language-env'
description: 'Extract the locale required for project construction'
author: 'wangdefu'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: false
    default: '1000'

# Define your outputs here.
outputs:
  language:
    description: 'the locale required for project construction'

runs:
  using: node20
  main: dist/index.js
