name: 'language-env'
description: 'Extract the locale required for project construction'
author: 'wangdefu'

# Define your inputs here.
inputs:
  serviceFilePath:
    description: 'serviceFilePath'
    required: false
    default: 'service.json'
  languageField:
    description: 'languageEnv'
    required: false
    default: 'languageEnv'
  languageVersionField:
    description: 'languageEnvVersion'
    required: false
    default: 'languageEnvVersion'

# Define your outputs here.
outputs:
  language:
    description: 'the locale required for project construction'

runs:
  using: node20
  main: dist/index.js
